# Generated by Django 3.2.5 on 2022-05-21 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=15)),
                ('duration', models.IntegerField()),
                ('primetime', models.DateField()),
                ('director', models.CharField(max_length=30)),
                ('writing', models.CharField(max_length=30)),
                ('crew', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Repertuar',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
