# Generated by Django 3.2.5 on 2022-05-21 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoProject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repertuar',
            name='t_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='djangoProject.movies'),
        ),
    ]
