# Generated by Django 4.0.4 on 2022-05-21 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoProject', '0002_repertuar_t_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repertuar',
            name='date',
        ),
        migrations.AddField(
            model_name='repertuar',
            name='date1',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='repertuar',
            name='date2',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='repertuar',
            name='date3',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='repertuar',
            name='date4',
            field=models.DateTimeField(null=True),
        ),
    ]
