# Generated by Django 3.2.5 on 2022-05-22 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoProject', '0003_remove_repertuar_date_repertuar_date1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='repertuar',
            name='av_tickets1',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='repertuar',
            name='av_tickets2',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='repertuar',
            name='av_tickets3',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='repertuar',
            name='av_tickets4',
            field=models.IntegerField(default=50),
        ),
    ]
