# Generated by Django 3.2.5 on 2022-05-22 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoProject', '0004_auto_20220522_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookings',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('data_rezerwacji', models.DateTimeField(auto_now_add=True)),
                ('typ', models.IntegerField(default=1)),
                ('count', models.IntegerField(default=1)),
                ('title', models.CharField(max_length=50)),
                ('date', models.DateTimeField(null=True)),
            ],
        ),
    ]
