# Generated by Django 3.2.5 on 2022-05-22 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoProject', '0007_tickets'),
    ]

    operations = [
        migrations.CreateModel(
            name='images',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='bookings',
            name='price',
            field=models.FloatField(default=19.9),
        ),
    ]
