# Generated by Django 3.2.5 on 2022-05-22 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoProject', '0008_auto_20220522_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='repertuar',
            name='im_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='djangoProject.images'),
        ),
    ]
