# Generated by Django 3.2.5 on 2022-05-22 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoProject', '0009_repertuar_im_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repertuar',
            name='im_id',
        ),
        migrations.AddField(
            model_name='movies',
            name='path',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='images',
        ),
    ]
