# Generated by Django 3.2.5 on 2022-05-23 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoProject', '0010_auto_20220522_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='count',
        ),
        migrations.RemoveField(
            model_name='bookings',
            name='price',
        ),
        migrations.RemoveField(
            model_name='bookings',
            name='typ',
        ),
        migrations.AddField(
            model_name='bookings',
            name='naleznosc',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bookings',
            name='normalny',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookings',
            name='rodzinny',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookings',
            name='szkolny',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookings',
            name='ulgowy',
            field=models.IntegerField(default=0),
        ),
    ]
