# Generated by Django 3.2.5 on 2022-05-23 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoProject', '0011_auto_20220523_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='movies',
            name='director',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='movies',
            name='title',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='movies',
            name='type',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='movies',
            name='writing',
            field=models.CharField(max_length=80),
        ),
    ]
