# Generated by Django 3.2.5 on 2022-06-01 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoProject', '0012_auto_20220523_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='r_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='djangoProject.repertuar'),
        ),
    ]
