# Generated by Django 3.2.5 on 2022-06-01 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoProject', '0013_bookings_r_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repertuar',
            options={'ordering': ('-id',)},
        ),
    ]
